<?php

namespace App\Http\Livewire\Client\Tables;

use App\Models\ClientLogs;
use Mediconesystems\LivewireDatatables\Http\Livewire\LivewireDatatable;
use Mediconesystems\LivewireDatatables\Column;
use App\Models\User;

class ClientLogTable extends LivewireDatatable
{
    public $client_id;
    public function mount($model = null, $include = [], $exclude = [], $hide = [], $dates = [], $times = [], $searchable = [], $sort = null, $hideHeader = null, $hidePagination = null, $perPage = 10, $exportable = false, $hideable = false, $beforeTableSlot = false, $afterTableSlot = false, $params = [])
    {
        $this->client_id = $params;
        //dd($this->client_id);
        parent::mount($model, $include, $exclude, $hide, $dates, $times, $searchable, $sort, $hideHeader, $hidePagination, $perPage, $exportable, $hideable, $beforeTableSlot, $afterTableSlot, $params); // TODO: Change the autogenerated stub
    }

    public function builder()
    {
        return ClientLogs::query()
            ->where('client_id',$this->client_id)->orderBy('created_at','desc');
    }

    public function columns()
    {
        return [
            Column::callback(['updated_by'], function ($updated_by) {
                return User::getUserNameByID($updated_by);
            })->label('Updated By'),

            Column::name('action_type')
                    ->label('Action Type'),

            Column::name('changes')
                ->label('Changes Made'),

            Column::name('created_at')
                ->label('Date'),

        ];
    }
}